### ISSUE TITLE
I've added HR support

### ISSUE THREAD

**Issue by morksinaanab** [lappalj4/react-native-easy-markdown#8]
Hey, 

I've added HR support. I'm new to pull requests and how that works, how would i do that?

I've done it here: http://github.com/morksinaanab/react-native-easy-markdown

**Comment by juiceo** [comment]
@morksinaanab please look here for instructions on how to create a pull request: https://help.github.com/articles/creating-a-pull-request-from-a-fork/ 

A few things you could fix before creating a PR: 

-  Please close the View tag since it has no children: instead of `<View></View>` do `<View/>`
- I would discourage using `width: '100%'`, you can achieve the same result with `alignSelf: 'stretch'`
- No need to give renderLine a third parameter in `renderNode` (Utils.concatStyles...) since it is not being used in `renderLine`.

Thanks for contributing, looking forward to your PR!
